include(../../shared.pri)

LIBS += -lQt5Sparql
QMAKE_RPATHDIR = $$QTSPARQL_BUILD_TREE/$$QTSPARQL_INSTALL_LIB $$QMAKE_RPATHDIR

EXAMPLES_DIR =

isEmpty(QTSPARQL_INSTALL_EXAMPLES) {
    EXAMPLES_DIR = $$[QT_INSTALL_EXAMPLES]/sparql/simple
} else {
    EXAMPLES_DIR = $$QTSPARQL_INSTALL_EXAMPLES
}
