include(../../shared.pri)

equals(QT_MAJOR_VERSION, 4): LIBS += -lQtSparql
equals(QT_MAJOR_VERSION, 5): LIBS += -lQt5Sparql
QMAKE_RPATHDIR = $$QTSPARQL_BUILD_TREE/lib $$QMAKE_RPATHDIR

EXAMPLES_DIR =

isEmpty($$QTSPARQL_INSTALL_EXAMPLES) {
    EXAMPLES_DIR = $$[QT_INSTALL_EXAMPLES]/sparql/simple
} else {
    EXAMPLES_DIR = $$QTSPARQL_INSTALL_EXAMPLES
}
