include(../../shared.pri)

LIBS += -lQtSparql
QMAKE_RPATHDIR = $$QT_BUILD_TREE/lib $$QMAKE_RPATHDIR

EXAMPLES_DIR =

isEmpty($$QTSPARQL_INSTALL_EXAMPLES) {
    EXAMPLES_DIR = $$[QT_INSTALL_EXAMPLES]/sparql/simple
} else {
    EXAMPLES_DIR = $$QTSPARQL_INSTALL_EXAMPLES
}
