######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 18 11:38:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sparql

# Input
FORMS += contact.ui list.ui add.ui main.ui
SOURCES += main.cpp
HEADERS += main.cpp
